import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('/Users/xinwei/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'/Users/xinwei/.cache/puppeteer/chrome-headless-shell/mac_arm-148.0.7778.97/chrome-headless-shell-mac-arm64/chrome-headless-shell'});
const page=await browser.newPage({viewport:{width:390,height:892}}),checks=[],errors=[];
const dir='prototype/qa/reference-refresh';await fs.mkdir(dir,{recursive:true});
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const check=(n,v)=>{assert.ok(v,n);checks.push(n);};
const shot=async name=>{await page.locator('#app').evaluate(e=>e.scrollTop=0);await page.locator('.phone').screenshot({path:`${dir}/${name}.png`,animations:'disabled',style:'.toast{visibility:hidden!important}'});};
try{
 await page.goto('http://127.0.0.1:8896/#home');await page.waitForSelector('#moment');
 await page.locator('#moment').fill('今天的小确幸');
 check('删除输入标题及多余提示',await page.locator('.home-composer>label').count()===0&&await page.locator('#moment').getAttribute('placeholder')==='分享此刻的故事…');
 check('添加照片入口至少50px高且横向撑满',await page.locator('.composer-upload').evaluate(e=>e.clientHeight>=48&&e.clientWidth>280));
 await page.locator('[data-action=upload]').click();await page.waitForSelector('.photo-source-modal[open]');
 check('相册与拍照两个入口',await page.locator('[data-action=choose-album]').count()===1&&await page.locator('[data-action=take-photo]').count()===1);await shot('photo-sources');
 const album=page.waitForEvent('filechooser');await page.locator('[data-action=choose-album]').click();const albumChooser=await album;check('相册可多选',albumChooser.isMultiple());await albumChooser.setFiles('prototype/assets/lifestyle-sheet.png');await page.waitForSelector('.composer-photo img');
 await page.locator('[data-action=upload]').click();const camera=page.waitForEvent('filechooser');await page.locator('[data-action=take-photo]').click();const cameraChooser=await camera;
 check('拍照使用后置摄像头单张入口',!cameraChooser.isMultiple()&&await page.locator('#camera').getAttribute('capture')==='environment');await cameraChooser.setFiles('prototype/assets/home-reference-hero.png');await page.waitForFunction(()=>KuaPrototype.store.getAccount().draft.photos.length===2);
 check('字数统计位于照片上方',await page.locator('.count').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('.composer-photos').getBoundingClientRect().top));
 check('照片位于文字输入框下方',await page.locator('.composer-photos').evaluate(e=>e.getBoundingClientRect().top>=document.querySelector('#moment').getBoundingClientRect().bottom));
 check('照片与添加入口间距不超过12px',await page.locator('.composer-upload').evaluate(e=>e.getBoundingClientRect().top-document.querySelector('.composer-photo').getBoundingClientRect().bottom<=12));
 check('选择照片保留配文',await page.locator('#moment').inputValue()==='今天的小确幸');await shot('home-photos');
 await page.locator('[data-action=upload]').click();await page.locator('.photo-source-cancel').click();check('取消选择保留两张照片',await page.locator('.composer-photo').count()===2);
 await page.evaluate(()=>{const s=KuaPrototype.store;s.setDraft({text:'第一份生活记录',photos:['sample:5']});const j=s.submitJob();s.finishJob(j.id,{title:'路边的小花开了',body:'把这一刻的温暖，好好留下。'},j.attempt);const raw=s.getState(),a=raw.accounts.a,t=Date.now();a.jobs=Array.from({length:12},(_,i)=>({...a.jobs[0],id:'ref-'+i,createdAt:t-i*86400000,finishedAt:t-i*86400000,title:['路边的小花开了','生活里的小确幸','谢谢你一直陪着我'][i%3],photos:['sample:'+([5,4,0][i%3])]}));a.draft.text='';a.draft.photos=[];a.plan={id:'ref-plan',remaining:28,expiresAt:t+30*86400000};a.free=0;const today=s.checkinSummary().today,yesterday=new Date(Date.parse(today+'T00:00:00Z')-86400000).toISOString().slice(0,10);a.checkinDays=[today,yesterday];localStorage.setItem('kua-yikua:model:v1',JSON.stringify(raw));localStorage.setItem('kua-yikua:login:v1',JSON.stringify({a:true}));});
 await page.reload();await page.waitForSelector('.recent-card');check('最近最多10条',await page.locator('.recent-card').count()===10);await shot('home');
 for(const route of ['records','profile','plan']){await page.goto('http://127.0.0.1:8896/#'+route);await page.waitForSelector('.'+(route==='records'?'record':route==='profile'?'quota-card':'plan-card'));if(route==='records')await page.waitForSelector('.record-photo canvas');await shot(route);check(route+' 无水平溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('#app').scrollWidth<=document.querySelector('#app').clientWidth));}
 for(const [state,plan,count,label] of [['new',null,30,'未开通'],['active',{id:'plan',remaining:28,expiresAt:Date.now()+86400000},28,'使用中'],['exhausted',{id:'plan',remaining:0,expiresAt:Date.now()+86400000},0,'次数已用完'],['expired',{id:'plan',remaining:5,expiresAt:Date.now()-1000},0,'已到期']]){await page.evaluate(plan=>{const raw=KuaPrototype.store.getState();raw.accounts.a.plan=plan;localStorage.setItem('kua-yikua:model:v1',JSON.stringify(raw));},plan);await page.reload();await page.waitForSelector('.plan-number');check(state+'套餐数据正确',(await page.locator('.plan-number').innerText()).startsWith(String(count))&&(await page.locator('.plan-label .badge').innerText())===label);check(state+'开通状态正确',await page.locator('[data-action=purchase]').isDisabled()===(state==='active'));if(state==='active'){await page.setViewportSize({width:320,height:820});await shot('plan-320');check('320px套餐无横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:390,height:892});}}
 await page.locator('[data-action=purchase]').click();await page.waitForSelector('[data-action=confirm-purchase]');await page.locator('[data-action=confirm-purchase]').click();check('重新开通仍走原有逻辑',await page.evaluate(()=>KuaPrototype.store.allowance().plan===30));
 await page.setViewportSize({width:320,height:820});for(const route of ['home','records','profile']){await page.goto('http://127.0.0.1:8896/#'+route);await page.waitForSelector('#app .page');if(route==='records')await page.waitForSelector('.record-photo canvas');await shot(route+'-320');check(route+' 320px不横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('#app').scrollWidth<=document.querySelector('#app').clientWidth));}
 await page.goto('http://127.0.0.1:8896/#plan');await page.waitForSelector('.plan-page');check('套餐已删除指定提示文案',!(/五种生活场景|免费体验剩余|免费体验另余|留住瞬间|贴近生活|一键分享|随时回看|连续记录/.test(await page.locator('.plan-page').innerText())));check('套餐胶囊靠右',await page.locator('.plan-page .nav').evaluate(e=>Math.abs(e.getBoundingClientRect().right-e.querySelector('.mini-capsule').getBoundingClientRect().right)<1));
 check('无页面错误',errors.length===0);await fs.writeFile(dir+'/report.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));
}finally{await browser.close();}
