import {demoDraftFixture} from './auth-fixture.mjs';
import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('/Users/xinwei/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'/Users/xinwei/.cache/puppeteer/chrome-headless-shell/mac_arm-148.0.7778.97/chrome-headless-shell-mac-arm64/chrome-headless-shell'});
const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();
const dir='prototype/qa/wechat-login',checks=[],errors=[];
await fs.mkdir(dir,{recursive:true});
page.on('pageerror',e=>errors.push(e.message));
const check=(name,value)=>{assert.ok(value,name);checks.push(name);};
const state=()=>page.evaluate(()=>window.KuaPrototype.store.getAccount());
const route=async r=>{await page.evaluate(r=>{location.hash=r;},r);await page.waitForSelector('.page');};
const shot=name=>page.screenshot({path:`${dir}/${name}.png`,animations:'disabled',style:'.toast{visibility:hidden!important}'});
await demoDraftFixture(page);
try{
 await page.goto('http://127.0.0.1:8896/#home');await page.waitForSelector('.photo-area img');
 check('游客首页不强制登录',await page.locator('dialog[open]').count()===0);
 await page.locator('#moment').fill('');await page.locator('[data-action="generate"]').click();
 check('先验证输入再请求登录',await page.locator('dialog[open]').count()===0);
 await page.locator('#moment').fill('今天做了面包，想记住这个小瞬间。');const draft=(await state()).draft;
 await page.locator('.profile-entry').click();await page.waitForSelector('.login-page');await shot('profile-guest');
 check('我的未登录时不显示记录和额度',await page.locator('.quota-card,.row-button').count()===0);
 await page.locator('.login-later[data-route="home"]').click();await page.locator('[data-action="generate"]').click();await page.waitForSelector('dialog.login-modal[open]');await shot('login-modal');
 check('无手机号或头像必填项',await page.locator('dialog input').count()===0);
 check('授权引导在生成首页内且主按钮明确续接生成',page.url().endsWith('#home')&&await page.locator('[data-action="confirm-login"]').innerText()==='微信授权并生成');
 await page.locator('dialog .login-later[data-action="close"]').click();
 check('取消登录保留草稿',JSON.stringify((await state()).draft)===JSON.stringify(draft));
 await page.locator('[data-action="generate"]').click();
 check('登录前不建任务不扣次',(await state()).jobs.length===0&&(await state()).free===3);
 await page.locator('[data-action="confirm-login"]').click();await page.locator('dialog .login-later[data-action="close"]').click();
 await page.waitForTimeout(550);
 check('登录等待中取消不会继续提交',(await state()).jobs.length===0&&await page.evaluate(()=>localStorage.getItem('kua-yikua:login:v1')===null));
 await page.locator('[data-action="generate"]').click();await context.setOffline(true);
 await page.locator('[data-action="confirm-login"]').click();await page.waitForSelector('.login-error:not([hidden])');await shot('login-failed');
 check('断网失败可重试且保留草稿',await page.locator('[data-action="confirm-login"]').isEnabled()&&JSON.stringify((await state()).draft)===JSON.stringify(draft)&&(await state()).free===3);
 await context.setOffline(false);
 await page.locator('[data-action="confirm-login"]').evaluate(b=>{b.click();b.click();});
 await page.waitForSelector('dialog [data-action="continue-recording"]');
 check('登录成功自动续接一次制作',(await state()).jobs.length===1&&(await state()).free===2);
 check('登录未修改输入',JSON.stringify((await state()).draft)===JSON.stringify(draft));
 await page.locator('dialog [data-route="records"]').click();await page.waitForSelector('.record');
 await page.reload();await page.waitForSelector('.record');
 check('刷新保持本地登录和已有任务',(await state()).jobs.length===1);
 await page.evaluate(()=>localStorage.removeItem('kua-yikua:login:v1'));await page.reload();await page.waitForSelector('.login-page');
 check('未登录深链接不展示私人记录',await page.locator('.record').count()===0);
 await page.locator('[data-action="login"]').click();await page.waitForSelector('.record');
 check('从记录登录回到原页且不额外提交',page.url().endsWith('#records')&&(await state()).jobs.length===1&&(await state()).free===2);
 await route('guide');await page.locator('[data-account="b"]').click();await route('profile');await page.waitForSelector('.login-page');
 check('另一个账号需要自己的登录状态',await page.locator('.quota-card').count()===0);
 await page.locator('[data-action="login"]').click();await page.waitForSelector('.quota-card');
 check('登录不复制其他账号记录',(await state()).jobs.length===0&&(await state()).free===3);
 await route('guide');await page.locator('[data-account="a"]').click();await route('profile');await page.waitForSelector('.quota-card');
 check('再次登录不重置历史与免费额度',(await state()).jobs.length===1&&(await state()).free===2);
 await page.evaluate(()=>localStorage.removeItem('kua-yikua:login:v1'));await page.reload();await page.waitForSelector('.login-page');
 await page.locator('.login-later[data-route="home"]').click();await page.locator('[data-action="generate"]').click();
 for(const [width,height] of [[360,540],[1440,600]]){
  await page.setViewportSize({width,height});
  await page.waitForFunction(()=>{const r=document.querySelector('dialog').getBoundingClientRect(),p=document.querySelector('.phone').getBoundingClientRect();return r.left>=p.left+12&&r.right<=p.right-12&&r.top>=Math.max(0,p.top)+12&&r.bottom<=Math.min(innerHeight,p.bottom)-12;});
  check(`${width}×${height} 登录弹窗在手机可见边界内`,await page.locator('dialog').evaluate(d=>d.scrollWidth<=d.clientWidth&&d.querySelector('.login-later').getBoundingClientRect().bottom<=d.getBoundingClientRect().bottom));
 }
 await shot('login-desktop-short');
 check('浏览器无页面异常',errors.length===0);
 await fs.writeFile(`${dir}/report.json`,JSON.stringify({checkedAt:new Date().toISOString(),checks,errors},null,2));
 console.log(JSON.stringify({passed:checks.length,errors},null,2));
}finally{await browser.close();}
